# Generated by Django 5.2.15 on 2026-08-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("DIRECTOR", "Director"),
                    ("TEACHER", "Docente / Revisor"),
                    ("STUDENT", "Alumno"),
                ],
                db_index=True,
                default="STUDENT",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
