# Generated by Django 5.2.15 on 2026-08-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Alumnos auto-registrados inician deshabilitados hasta que un docente los habilite.",
                verbose_name="Habilitado para subir documentos",
            ),
        ),
    ]
