# Generated by Django 5.2.15 on 2026-06-26 19:42

import apps.certificates.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=40,
                        unique=True,
                        verbose_name="Código de certificado",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.certificates.models.certificate_upload_path,
                        verbose_name="PDF del certificado",
                    ),
                ),
                (
                    "verification_hash",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        verbose_name="Hash de verificación",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revocado el"
                    ),
                ),
                (
                    "revoke_reason",
                    models.TextField(blank=True, verbose_name="Motivo de revocación"),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Emitido por",
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificate",
                        to="reports.analysisreport",
                        verbose_name="Reporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="certificate_code_b5c6e8_idx"),
                    models.Index(
                        fields=["verification_hash"],
                        name="certificate_verific_1316c6_idx",
                    ),
                    models.Index(
                        fields=["is_active", "created_at"],
                        name="certificate_is_acti_dabdf7_idx",
                    ),
                ],
            },
        ),
    ]
