# Generated by Django 5.2.15 on 2026-06-26 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Similitud + IA"),
                            ("SIMILARITY", "Solo similitud"),
                            ("AI_DETECTION", "Solo detección IA"),
                        ],
                        db_index=True,
                        default="FULL",
                        max_length=30,
                        verbose_name="Tipo de análisis",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("QUEUED", "En cola"),
                            ("RUNNING", "Ejecutando"),
                            ("SUCCESS", "Exitoso"),
                            ("FAILED", "Fallido"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Número de intento"
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="ID de tarea Celery",
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Paso actual"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado el"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizado el"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Código de error"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_jobs",
                        to="documents.document",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_analysis_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajo de análisis",
                "verbose_name_plural": "Trabajos de análisis",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "status"],
                        name="analysis_an_documen_3ef9c2_idx",
                    ),
                    models.Index(
                        fields=["requested_by", "created_at"],
                        name="analysis_an_request_3157f5_idx",
                    ),
                    models.Index(
                        fields=["celery_task_id"], name="analysis_an_celery__66941a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "analysis_type", "attempt_number"),
                        name="unique_analysis_attempt_per_document",
                    )
                ],
            },
        ),
    ]
