# Generated by Django 5.2.15 on 2026-07-14 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentKnowledgeChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                ("text_excerpt", models.TextField(verbose_name="Fragmento original")),
                (
                    "normalized_text",
                    models.TextField(verbose_name="Fragmento normalizado"),
                ),
                (
                    "start_offset",
                    models.PositiveIntegerField(verbose_name="Inicio en texto"),
                ),
                (
                    "end_offset",
                    models.PositiveIntegerField(verbose_name="Fin en texto"),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad de palabras"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Hash del fragmento"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_chunks",
                        to="documents.document",
                        verbose_name="Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fragmento aprendido",
                "verbose_name_plural": "Fragmentos aprendidos",
                "indexes": [
                    models.Index(
                        fields=["document", "is_active"],
                        name="analysis_do_documen_8cae51_idx",
                    ),
                    models.Index(
                        fields=["content_hash"], name="analysis_do_content_ba47da_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="analysis_do_created_c94067_idx"
                    ),
                ],
            },
        ),
    ]
