# Generated by Django 5.2.15 on 2026-08-04 05:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_documentknowledgechunk"),
    ]

    operations = [
        migrations.CreateModel(
            name="OaiRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "repository_name",
                    models.CharField(
                        max_length=180, verbose_name="Nombre del repositorio"
                    ),
                ),
                (
                    "repository_domain",
                    models.CharField(
                        db_index=True,
                        max_length=180,
                        verbose_name="Dominio del repositorio",
                    ),
                ),
                (
                    "oai_identifier",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Identificador OAI",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Título")),
                ("authors", models.TextField(blank=True, verbose_name="Autores")),
                (
                    "source_url",
                    models.URLField(blank=True, verbose_name="URL de origen"),
                ),
                ("text_excerpt", models.TextField(verbose_name="Fragmento original")),
                (
                    "normalized_text",
                    models.TextField(verbose_name="Fragmento normalizado"),
                ),
                ("harvested_at", models.DateTimeField(verbose_name="Cosechado el")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro OAI",
                "verbose_name_plural": "Registros OAI",
                "indexes": [
                    models.Index(
                        fields=["repository_domain", "is_active"],
                        name="analysis_oa_reposit_5eb379_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analysis_oa_created_4fcf72_idx"
                    ),
                ],
            },
        ),
    ]
