# Generated by Django 5.2.15 on 2026-08-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_oairecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.BigIntegerField(db_index=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("internal", "internal"), ("oai", "oai")],
                        max_length=20,
                    ),
                ),
                ("source_id", models.UUIDField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["hash"], name="analysis_do_hash_457105_idx"),
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="analysis_do_source__8f24f5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hash", "source_type", "source_id"),
                        name="uniq_fingerprint_per_source",
                    )
                ],
            },
        ),
    ]
