# Generated by Django 5.2.15 on 2026-08-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_documentfingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='oairecord',
            name='source_date',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Fecha de publicación (dc:date)'),
        ),
    ]
