# Generated by Django 5.2.15 on 2026-06-26 19:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=180, unique=True, verbose_name="Nombre institucional"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="Identificador URL"
                    ),
                ),
                (
                    "ruc",
                    models.CharField(blank=True, max_length=20, verbose_name="RUC"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="private/institutions/logos/",
                        verbose_name="Logo institucional",
                    ),
                ),
                (
                    "certificate_signature_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nombre de firmante"
                    ),
                ),
                (
                    "certificate_signature_position",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Cargo de firmante"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
                "ordering": ["name"],
            },
        ),
    ]
