# Generated by Django 5.2.15 on 2026-08-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="email_domain",
            field=models.CharField(
                blank=True,
                help_text="Ej: iesp-alfonsobarranteslingan.edu.pe (sin @ ni subdominios)",
                max_length=120,
                verbose_name="Dominio de correo institucional",
            ),
        ),
    ]
