# Generated by Django 5.2.15 on 2026-08-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_institution_email_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="short_code",
            field=models.CharField(
                blank=True,
                help_text="Usado como prefijo de certificados, ej: IESPPABL",
                max_length=15,
                verbose_name="Código corto institucional",
            ),
        ),
    ]
