# Generated by Django 5.2.15 on 2026-06-26 19:42

import apps.documents.models
import apps.documents.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=250, verbose_name="Título"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("THESIS", "Tesis"),
                            ("MONOGRAPH", "Monografía"),
                            ("ESSAY", "Ensayo"),
                            ("RESEARCH_ARTICLE", "Artículo de investigación"),
                            ("OTHER", "Otro"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=30,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        blank=True,
                        max_length=180,
                        verbose_name="Curso / Unidad didáctica",
                    ),
                ),
                (
                    "academic_period",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Periodo académico"
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        upload_to=apps.documents.models.document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("pdf", "docx")
                            ),
                            apps.documents.validators.validate_document_size,
                            apps.documents.validators.validate_document_mime_type,
                        ],
                        verbose_name="Archivo original",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        max_length=255, verbose_name="Nombre original del archivo"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        max_length=120, verbose_name="MIME type detectado"
                    ),
                ),
                (
                    "file_size_bytes",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Tamaño en bytes",
                    ),
                ),
                (
                    "sha256_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Hash SHA-256"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        db_index=True,
                        default="es",
                        max_length=10,
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Subido"),
                            ("QUEUED", "En cola"),
                            ("PROCESSING", "Procesando"),
                            ("COMPLETED", "Completado"),
                            ("FAILED", "Fallido"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="core.institution",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alumno / propietario",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentText",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                ("content", models.TextField(verbose_name="Texto extraído")),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad de palabras"
                    ),
                ),
                (
                    "character_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad de caracteres"
                    ),
                ),
                (
                    "extraction_engine",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Motor de extracción"
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Extraído el"
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_text",
                        to="documents.document",
                        verbose_name="Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Texto extraído",
                "verbose_name_plural": "Textos extraídos",
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["institution", "status"], name="documents_d_institu_cf3602_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["institution", "created_at"],
                name="documents_d_institu_4790f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["owner", "created_at"], name="documents_d_owner_i_db5cd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["sha256_hash"], name="documents_d_sha256__1b7de8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("file_size_bytes__gte", 1)),
                name="document_file_size_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="documenttext",
            index=models.Index(
                fields=["document"], name="documents_d_documen_b35614_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttext",
            index=models.Index(
                fields=["word_count"], name="documents_d_word_co_b14d24_idx"
            ),
        ),
    ]
