# Generated by Django 5.2.15 on 2026-08-09 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="advisor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["TEACHER", "DIRECTOR"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advised_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asesor",
            ),
        ),
    ]
