# Generated by Django 5.2.15 on 2026-06-26 19:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "similarity_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Porcentaje de similitud",
                    ),
                ),
                (
                    "web_similarity_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Similitud web",
                    ),
                ),
                (
                    "internal_similarity_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Similitud interna",
                    ),
                ),
                (
                    "ai_probability_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Probabilidad de IA",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Bajo"),
                            ("MEDIUM", "Medio"),
                            ("HIGH", "Alto"),
                            ("CRITICAL", "Crítico"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=20,
                        verbose_name="Nivel de riesgo",
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Resumen técnico"
                    ),
                ),
                (
                    "engine_version",
                    models.CharField(
                        default="vql-mvp-1.0.0",
                        max_length=80,
                        verbose_name="Versión del motor",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Generado el",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Reporte final"
                    ),
                ),
                (
                    "analysis_job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report",
                        to="analysis.analysisjob",
                        verbose_name="Trabajo de análisis",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="documents.document",
                        verbose_name="Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de análisis",
                "verbose_name_plural": "Reportes de análisis",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("WEB", "Fuente web"),
                            ("INTERNAL", "Base interna"),
                            ("REPOSITORY", "Repositorio académico"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de fuente",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300, verbose_name="Título de la fuente"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=1000, verbose_name="URL"),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=180,
                        verbose_name="Dominio",
                    ),
                ),
                (
                    "matched_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Porcentaje coincidente",
                    ),
                ),
                (
                    "snippet",
                    models.TextField(blank=True, verbose_name="Fragmento coincidente"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="reports.analysisreport",
                        verbose_name="Reporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuente del reporte",
                "verbose_name_plural": "Fuentes del reporte",
                "ordering": ["-matched_percent"],
            },
        ),
        migrations.CreateModel(
            name="ReportFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("SIMILARITY", "Similitud"),
                            ("AI_GENERATED", "Posible texto generado por IA"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Tipo de hallazgo",
                    ),
                ),
                (
                    "start_offset",
                    models.PositiveIntegerField(verbose_name="Inicio en texto"),
                ),
                (
                    "end_offset",
                    models.PositiveIntegerField(verbose_name="Fin en texto"),
                ),
                ("text_excerpt", models.TextField(verbose_name="Texto detectado")),
                (
                    "confidence_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Confianza",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos técnicos"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="reports.analysisreport",
                        verbose_name="Reporte",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="reports.reportsource",
                        verbose_name="Fuente asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hallazgo del reporte",
                "verbose_name_plural": "Hallazgos del reporte",
                "ordering": ["start_offset"],
            },
        ),
        migrations.AddIndex(
            model_name="analysisreport",
            index=models.Index(
                fields=["risk_level", "generated_at"],
                name="reports_ana_risk_le_396417_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysisreport",
            index=models.Index(
                fields=["similarity_percent"], name="reports_ana_similar_9249c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisreport",
            index=models.Index(
                fields=["ai_probability_percent"], name="reports_ana_ai_prob_25f716_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportsource",
            index=models.Index(
                fields=["report", "source_type"], name="reports_rep_report__e0f61e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportsource",
            index=models.Index(fields=["domain"], name="reports_rep_domain_124065_idx"),
        ),
        migrations.AddIndex(
            model_name="reportfinding",
            index=models.Index(
                fields=["report", "finding_type"], name="reports_rep_report__67ea2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportfinding",
            index=models.Index(
                fields=["start_offset", "end_offset"],
                name="reports_rep_start_o_0b577c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportfinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_offset__gt", models.F("start_offset"))),
                name="finding_end_offset_greater_than_start",
            ),
        ),
    ]
