# Generated by Django 5.2.15 on 2026-08-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='ai_detector',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Detector de IA utilizado'),
        ),
    ]
