# Generated by Django 5.2.15 on 2026-09-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_analysisreport_ai_detector"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="analyzed_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Texto sobre el que se calcularon los offsets de los hallazgos (sin portada/índice/bibliografía). El visor y el PDF señalado pintan los resaltados sobre este texto, no sobre el crudo, para que coincidan exactamente.",
                verbose_name="Texto analizado (filtrado)",
            ),
        ),
    ]
